replicaCount: 1

image:
  repository: sergeyarenzon/huddlehub-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: true
  className: nginx
  host: localhost
  paths:
    - path: /api/v1/user(/|$)(.*)
      pathType: ImplementationSpecific
      serviceName: user
      servicePort: 3000
    - path: /api/v1/auth(/|$)(.*)
      pathType: ImplementationSpecific
      serviceName: auth
      servicePort: 3000
    - path: /api/v1/tour(/|$)(.*)
      pathType: ImplementationSpecific
      serviceName: tour
      servicePort: 3000
    - path: /api/v1/reservation(/|$)(.*)
      pathType: ImplementationSpecific
      serviceName: booking
      servicePort: 3000

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 150Mi 