{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: DirectoryOrCreate
{{- end }}

