apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "profile-db.fullname" . }}-config
  labels:
    {{- include "profile-db.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }} 