{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "profile-db.fullname" . }}-pv
  labels:
    {{- include "profile-db.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: DirectoryOrCreate
{{- end }} 