apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  JWT_MAX_AGE: {{ .Values.env.JWT_MAX_AGE | quote }} 
  JWT_ACCESS_EXPIRES_IN_MS: {{ .Values.env.JWT_ACCESS_EXPIRES_IN_MS | quote }}
  JWT_REFRESH_EXPIRES_IN_MS: {{ .Values.env.JWT_REFRESH_EXPIRES_IN_MS | quote }}
  GOOGLE_REDIRECT_URI: {{ .Values.env.GOOGLE_REDIRECT_URI | quote }}