apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ include "auth.fullname" . }}-db-job'
  labels:
    app: {{ include "auth.fullname" . }}
    job: database
  # annotations:
    # Add a skaffold annotation to force recreation
    # "skaffold.dev/depends-on-image1": "{{ .Values.image.repository }}"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "auth.fullname" . }}
        job: database
    spec:
      initContainers:
        - name: check-auth-db-ready
          image: busybox:latest
          command: ['sh', '-c', 
            'until nc -z -w1 {{ index .Values.configMaps "auth-db" "keys" "POSTGRES_HOST" }} {{ index .Values.configMaps "auth-db" "keys" "POSTGRES_PORT" }}; 
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: database
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              echo "Running DB migrations..." &&
              npx mikro-orm migration:up
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ index .Values.configMaps "auth-db" "name" | quote }}
                  key: POSTGRES_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ index .Values.configMaps "auth-db" "name" | quote }}
                  key: POSTGRES_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ index .Values.configMaps "auth-db" "name" | quote }}
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ index .Values.configMaps "auth-db" "name" | quote }}
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values.secrets "global" "name" | quote }}
                  key: {{ index .Values.secrets "global" "keys" "jwt-secret" | quote }}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ index .Values.configMaps "global" "name" | quote }}
                  key: {{ index .Values.configMaps "global" "keys" "redis-host" | quote }}
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ index .Values.configMaps "global" "name" | quote }}
                  key: {{ index .Values.configMaps "global" "keys" "redis-port" | quote }}
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ index .Values.configMaps "global" "name" | quote }}
                  key: {{ index .Values.configMaps "global" "keys" "redis-db" | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ index .Values.secrets "global" "name" | quote }}
                  key: {{ index .Values.secrets "global" "keys" "redis-password" | quote }}
      restartPolicy: Never

