## Official PostgreSQL chart configuration for auth service
## Override the name of the chart
fullnameOverride: "auth-db"

image:
  repository: postgres
  tag: 15.3 
  pullPolicy: IfNotPresent

auth:
  username: postgres
  password: postgres
  database: auth
  postgresPassword: postgres

persistence:
  enabled: true
  storageClass: auth-db-storage-class
  size: 1Gi
  accessMode: ReadWriteOnce
  hostPath: /var/lib/postgresql/auth-data

primary:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 150Mi

# Use default PostgreSQL port 5432
service:
  ports:
    postgresql: 5432

metrics:
  enabled: false 