secrets:
  jwt:
    secret: "2z7hj/ieyygTYBJ8BAmCEFykx+zCnR321y8w5tNkI8foQ2Mpt5ManPKkmgtc08nTkxwHPg1PT2aoxkTR2x3SgA=="
  redis:
    password: "redis"
configMaps:
  redis:
    host: "redis-master"
    port: "6379"
    db: "0" 