apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  redis-host: {{ .Values.configMaps.redis.host | quote }}
  redis-port: {{ .Values.configMaps.redis.port | quote }}
  redis-db: {{ .Values.configMaps.redis.db | quote }}
  base-url: {{ .Values.configMaps.baseUrl | quote }}
