apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwt.secret | b64enc | quote }}
  redis-password: {{ .Values.secrets.redis.password | b64enc | quote }}
  auth-google-client-id: {{ .Values.secrets.auth.googleClientId | b64enc | quote }}
  auth-google-client-secret: {{ .Values.secrets.auth.googleClientSecret | b64enc | quote }} 