apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  REDIS_HOST: {{ .Values.configMaps.redis.host | quote }}
  REDIS_PORT: {{ .Values.configMaps.redis.port | quote }}
  REDIS_DB: {{ .Values.configMaps.redis.db | quote }}
  BASE_URL: {{ .Values.configMaps.baseUrl | quote }}
  NOTIFICATION_QUEUE: {{ .Values.configMaps.rabbitmq.notificationQueue | quote }}
