replicaCount: 1

image:
  repository: sergeyarenzon/huddlehub-profile
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 150Mi

configMaps:
  profile-db:
    name: profile-db-config
    keys:
      POSTGRES_HOST: profile-db
      POSTGRES_PORT: "5432"

database:
  url: "postgresql://postgres:postgres@profile-db:5432/postgres?schema=public"
  host: "profile-db"
  port: 5432
  name: "profile"
  user: "postgres"
  password: "postgres"