apiVersion: v1
kind: Service
metadata:
  name: {{ template "profile-db.fullname" . }}
  labels:
    {{- include "profile-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "profile-db.selectorLabels" . | nindent 4 }} 