apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ include "booking.fullname" . }}-db-job'
  labels:
    app: {{ include "booking.fullname" . }}
    job: migration
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "booking.fullname" . }}
        job: migration
    spec:
      initContainers:
        - name: check-booking-db-ready
          image: busybox:latest
          command: ['sh', '-c', 
            'until nc -z -w1 {{ .Values.database.host }} {{ .Values.database.port }}; 
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          command: ["sh", "-c"]
          args:
            - |
              echo "Running DB migrations..." &&
              cd /app &&
              npx mikro-orm migration:up &&
              echo "Migrations completed successfully"
          env:
            - name: DATABASE_URL
              value: "{{ .Values.database.url }}"
      restartPolicy: Never
