replicaCount: 1

image:
  repository: sergeyarenzon/huddlehub-notification
  tag: latest
  pullPolicy: IfNotPresent

env:
  AMQP_URL: "amqp://admin:admin@rabbitmq:5672/"
  NOTIFICATION_QUEUE: "notifications"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
